var searchData=
[
  ['a_0',['a',['../structMyStruct.html#a74e3e5f5127308998259bd2adfa65c4a',1,'MyStruct']]],
  ['a_20single_20database_1',['Example of Using Multiple Classes with a Single Database',['../index.html#autotoc_md4',1,'']]],
  ['add_5fvalue_2',['add_value',['../namespacesqlite__containers.html#aa934244a802b49221cb7b5fa12b241b8',1,'sqlite_containers::add_value(ContainerT&lt; T &gt; &amp;container, T &amp;value, typename std::enable_if&lt; std::is_same&lt; ContainerT&lt; T &gt;, std::set&lt; T &gt; &gt;::value||std::is_same&lt; ContainerT&lt; T &gt;, std::unordered_set&lt; T &gt; &gt;::value &gt;::type *=0)'],['../namespacesqlite__containers.html#a756312d5dacb8ccf1a26db47087dcd6f',1,'sqlite_containers::add_value(ContainerT&lt; T &gt; &amp;container, const T &amp;value, const size_t &amp;value_count=0, typename std::enable_if&lt; std::is_same&lt; ContainerT&lt; T &gt;, std::multiset&lt; T &gt; &gt;::value||std::is_same&lt; ContainerT&lt; T &gt;, std::unordered_multiset&lt; T &gt; &gt;::value &gt;::type *=0)'],['../namespacesqlite__containers.html#ac242df8c3cc2926402cf2fe74b10a383',1,'sqlite_containers::add_value(ContainerT&lt; T &gt; &amp;container, T &amp;value, typename std::enable_if&lt; std::is_same&lt; ContainerT&lt; T &gt;, std::list&lt; T &gt; &gt;::value||std::is_same&lt; ContainerT&lt; T &gt;, std::vector&lt; T &gt; &gt;::value||std::is_same&lt; ContainerT&lt; T &gt;, std::deque&lt; T &gt; &gt;::value &gt;::type *=0)'],['../namespacesqlite__containers.html#a4519861ac004918234533624ee1640d0',1,'sqlite_containers::add_value(ContainerT&lt; T &gt; &amp;container, const T &amp;value, const size_t &amp;value_count, typename std::enable_if&lt; std::is_same&lt; ContainerT&lt; T &gt;, std::list&lt; T &gt; &gt;::value||std::is_same&lt; ContainerT&lt; T &gt;, std::vector&lt; T &gt; &gt;::value||std::is_same&lt; ContainerT&lt; T &gt;, std::deque&lt; T &gt; &gt;::value &gt;::type *=0)'],['../namespacesqlite__containers.html#a1ccb3ad96a48e56f609bd95f1dee63da',1,'sqlite_containers::add_value(ContainerT&lt; T &gt; &amp;container, const T &amp;value, const size_t &amp;value_count, typename std::enable_if&lt; std::is_same&lt; ContainerT&lt; T &gt;, std::set&lt; T &gt; &gt;::value||std::is_same&lt; ContainerT&lt; T &gt;, std::multiset&lt; T &gt; &gt;::value||std::is_same&lt; ContainerT&lt; T &gt;, std::unordered_set&lt; T &gt; &gt;::value||std::is_same&lt; ContainerT&lt; T &gt;, std::unordered_multiset&lt; T &gt; &gt;::value &gt;::type *=0)'],['../namespacesqlite__containers.html#a00d2219ff83c30e6c8f2b6a85f5e7762',1,'sqlite_containers::add_value(ContainerT&lt; KeyT, ValueT &gt; &amp;container, KeyT &amp;key, ValueT &amp;value, const size_t &amp;value_count, typename std::enable_if&lt; std::is_same&lt; ContainerT&lt; KeyT, ValueT &gt;, std::multimap&lt; KeyT, ValueT &gt; &gt;::value||std::is_same&lt; ContainerT&lt; KeyT, ValueT &gt;, std::unordered_multimap&lt; KeyT, ValueT &gt; &gt;::value &gt;::type *=0)']]],
  ['analysis_5flimit_3',['analysis_limit',['../classsqlite__containers_1_1Config.html#a1a1b554ac50ca35cc1f18b6dfe1c3d06',1,'sqlite_containers::Config']]],
  ['append_4',['append',['../classsqlite__containers_1_1KeyDB.html#a916f8522fc27a7b431c3fcd476a50cc9',1,'sqlite_containers::KeyDB::append(const ContainerT&lt; KeyT &gt; &amp;container)'],['../classsqlite__containers_1_1KeyDB.html#a5bf75261a3ffcfcf6454d54484a8ca3e',1,'sqlite_containers::KeyDB::append(const ContainerT&lt; KeyT &gt; &amp;container, const TransactionMode &amp;mode)'],['../classsqlite__containers_1_1KeyMultiValueDB.html#a24ee78145c7a430f79e6029de5c1fa68',1,'sqlite_containers::KeyMultiValueDB::append(const ContainerT&lt; KeyT, ValueT &gt; &amp;container, const TransactionMode &amp;mode)'],['../classsqlite__containers_1_1KeyMultiValueDB.html#ab14ff86f477cc7a14f4f99e777fe8c7a',1,'sqlite_containers::KeyMultiValueDB::append(const ContainerT&lt; KeyT, ValueT &gt; &amp;container)'],['../classsqlite__containers_1_1KeyMultiValueDB.html#a8d406654c6e76c3523d27d724cb96be3',1,'sqlite_containers::KeyMultiValueDB::append(const ContainerT&lt; KeyT, ValueContainerT&lt; ValueT &gt; &gt; &amp;container, const TransactionMode &amp;mode)'],['../classsqlite__containers_1_1KeyMultiValueDB.html#acc37f4beeb5cd45bf95851f84a96e0ca',1,'sqlite_containers::KeyMultiValueDB::append(const ContainerT&lt; KeyT, ValueContainerT&lt; ValueT &gt; &gt; &amp;container)'],['../classsqlite__containers_1_1KeyValueDB.html#aae2ce8197b394c68eeae04666c1b3ac5',1,'sqlite_containers::KeyValueDB::append(const ContainerT&lt; KeyT, ValueT &gt; &amp;container)'],['../classsqlite__containers_1_1KeyValueDB.html#ace380fc77c4ff79602754483440f4381',1,'sqlite_containers::KeyValueDB::append(const ContainerT&lt; KeyT, ValueT &gt; &amp;container, const TransactionMode &amp;mode)']]],
  ['auto_5fvacuum_5fmode_5',['auto_vacuum_mode',['../classsqlite__containers_1_1Config.html#a363d152e86343e95c8c7366fc4d6bde7',1,'sqlite_containers::Config']]],
  ['autovacuummode_6',['AutoVacuumMode',['../namespacesqlite__containers.html#ac4f2da88cbcec2e9f68fcf5fbaeede82',1,'sqlite_containers']]]
];
